### ISSUE TITLE
Bullseye repo broken

### ISSUE THREAD

**Issue by fredericve** [regolith-linux/package-repo#2]
I have this in my sources.list file:

```
deb [arch=amd64] https://regolith-linux.github.io/package-repo/release/debian/bullseye/amd64 bullseye main
```
When running `apt update` I get this output

```
Ign:5 https://regolith-linux.github.io/package-repo/release/debian/bullseye/amd64 bullseye InRelease                                            
Err:8 https://regolith-linux.github.io/package-repo/release/debian/bullseye/amd64 bullseye Release                                              
  404  Not Found [IP: 185.199.109.153 443]
E: The repository 'https://regolith-linux.github.io/package-repo/release/debian/bullseye/amd64 bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
This did not used to be the case (looks like the layout of the repo changed as well).

**Comment by kgilmer** [comment]
Hi @fredericve , yes the repo layout changed to accommodate _release stages_.  This means that there is now an additional path element in the Debian apt URL.  The README is updated with (I believe to be) valid URLs.  Can you update and kindly re-open the ticket if that does not resolve your problem?

Also, thanks for testing the pre-alpha Regolith 2 release.  I'd be curious if you have any thoughts or other feedback, in particular the [new launcher](https://github.com/regolith-linux/ilia).

**Comment by fredericve** [comment]
@kgilmer I did update my sources.list file with the suggested content in the README file before creating the issue ;-)

So yeah it still does not work for me.

**Comment by kgilmer** [comment]
Ah, the problem is that there is nothing in the `release` stage yet.  I'll update the readme but this is the apt line you want:

```
Bad:    https://regolith-linux.github.io/package-repo/release/debian/bullseye/amd64
Good:  https://regolith-linux.github.io/package-repo/unstable/debian/bullseye/amd64
```

**Comment by fredericve** [comment]
Ah yes that makes sense. Works fine now of course. Thanks.
